CXX = g++
CXXFLAGS := -std=c++20 -Wall -Wextra -Werror -pedantic -Iheader -Icommon
LDFLAGS = -shared

TARGET = GameManager_098765432_123456789.so
SRC = GameManager.cpp
OBJ = $(SRC:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(LDFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)

.PHONY: all clean